"""empty message

Revision ID: 742df24997d6
Revises: 
Create Date: 2026-02-24 18:06:37.258090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '742df24997d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaultentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaultentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaultentry_site_name'), ['site_name'], unique=False)

    op.create_table('ghostcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vault_id'], ['vaultentry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ghostcard')
    with op.batch_alter_table('vaultentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaultentry_site_name'))

    op.drop_table('vaultentry')
    # ### end Alembic commands ###
